config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games, only: [:index, :show, :create] do
    resources :guesses, only: [:create, :index]
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player_target, required: true
  has_many :guesses, dependent: :destroy

  validates :status, presence: true
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game
  belongs_to :player_target, foreign_key: 'target_id', optional: true

  validates :first_name, :last_name, :game_id, presence: true

  after_create :check_guess

  private

  def check_guess
    return unless player_target.present?

    game_target = game.player_target
    if player_target.stats_api_id == game_target.stats_api_id
      game.update(found_player: true, found_position: true, found_team: true,
                  found_throwing_hand: true, found_batting_hand: true,
                  found_league: true, found_jersey_number: true,
                  status: 'completed')
    else
      if player_target.position == game_target.position
        game.update(found_position: true)
      end
      if player_target.team_name == game_target.team_name
        game.update(found_team: true)
      end
      if player_target.throwing_hand == game_target.throwing_hand
        game.update(found_throwing_hand: true)
      end
      if player_target.batting_hand == game_target.batting_hand
        game.update(found_batting_hand: true)
      end
      if player_target.league == game_target.league
        game.update(found_league: true)
      end
      if player_target.jersey_number == game_target.jersey_number
        game.update(found_jersey_number: true)
      end
    end
  end
end

app/models/player_target.rb
class PlayerTarget < ApplicationRecord
  has_many :games, dependent: :destroy

  validates :stats_api_id, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :position, presence: true
  validates :batting_hand, presence: true
  validates :throwing_hand, presence: true
  validates :team_name, presence: true
  validates :league, presence: true
end

app/models/player_target_factory.rb
# frozen_string_literal: true

class PlayerTargetFactory

  def self.get_random_player_target
    stats_client = StatsClient.new
    random_team_id = Team.pluck(:stats_api_id).sample
    team_data = stats_client.get_team(random_team_id)
    roster_player_ids = team_data[:roster].map { |player| player[:person][:id] }
    random_player_id = roster_player_ids.sample
    player = PlayerTarget.find_by(stats_api_id: random_player_id.to_s)
    return player if player.present?

    player_data = stats_client.get_player(random_player_id)[:people][0]

    create_from_stats_api_data(player_data)
  end

  def self.get_player_target_by_name(name)
    stats_client = StatsClient.new
    search_result = stats_client.search_players_by_name(name)
    return nil if search_result[:people].blank?

    player_data = search_result[:people][0]
    create_from_stats_api_data(player_data)
  end

  def self.create_from_stats_api_data(data)
    player_target = PlayerTarget.find_or_initialize_by(stats_api_id: data[:id])
    player_target.first_name = data[:firstName]
    player_target.last_name = data[:lastName]
    player_target.jersey_number = data[:primaryNumber]
    player_target.position = data[:primaryPosition][:abbreviation]
    player_target.team_name = data[:currentTeam][:name]
    player_target.batting_hand = data[:batSide][:description]
    player_target.throwing_hand = data[:pitchHand][:description]
    player_target.league = 'NL'

    player_target.save
    player_target
  end

end

app/models/stats_client.rb
# frozen_string_literal: true
class StatsClient

  BASE_URL = 'https://statsapi.mlb.com/api/v1'

  attr_reader :conn

  def initialize
    @conn = Faraday.new(BASE_URL) do |builder|
      builder.response :json, parser_options: { symbolize_names: true }
      builder.adapter Faraday.default_adapter
    end
  end

  def get_team(stats_team_id)
    conn.get("teams/#{stats_team_id}/roster").body
  end

  def get_player(stats_player_id)
    conn.get("people/#{stats_player_id}?hydrate=rosterEntries,currentTeam").body
  end

  def search_players_by_name(name)
    conn.get("people/search", { names: name, limit: 1, hydrate: 'currentTeam' }).body
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def create
    @player_target = PlayerTargetFactory.get_random_player_target
    @game = Game.new(player_target: @player_target)
    if @game.save
      redirect_to game_path(id: @game.id), notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def show
    @game = Game.find(params[:id])
    @guesses = @game.guesses
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def create
    @guess_target = PlayerTargetFactory.get_player_target_by_name(params[:name])
    return unless @guess_target.present? && @guess_target.persisted?

    @game = Game.find(params[:game_id])
    @game.guesses.create(first_name: @guess_target.first_name,
                         last_name: @guess_target.last_name,
                         target_id: @guess_target.id)
    redirect_to game_path(id: params[:game_id])
  end

  def index
    @guesses = Guess.where(game_id: params[:game_id])
    render partial: 'game_guesses', locals: { guesses: @guesses }
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.slim
ul
  - @games.each do |game|
    li
      = "#{game.status} - Total Guesses: #{game.total_guesses}"
= button_to('Start New Game', games_path, method: :post, class: 'new-game-button')

app/views/games/show.html.slim
h1
  = @game.id
h2 Guess the player...
= turbo_frame_tag("guesses_frame") do
  ul
    li = "Status: #{@game.status}"
    li = "Total Guesses: #{@guesses.length}"
    li = "Found player: #{@game.found_player}"
    li = "Found league: #{@game.found_league}"
    li = "Found position: #{@game.found_position}"
    li = "Found team: #{@game.found_team}"
    li = "Found jersey number: #{@game.found_jersey_number}"
    li = "Found throwing hand: #{@game.found_throwing_hand}"
    li = "Found batting hand: #{@game.found_batting_hand}"

  .game-guess-form
    = form_with url: game_guesses_path(@game), method: :post, data: { turbo_frame: "guesses_frame"} do |form|
      = form.label :player_name, "Enter Player Name:"
      = form.text_field :name, required: true
      = form.submit "Submit Guess"

  .guesses-list
    h3 Previous Guesses:
    - @guesses.each do |guess|
      .guess-item
        = "Guess: #{guess.first_name} #{guess.last_name}, #{guess.player_target.position}, #{guess.player_target.team_name}"

app/views/guesses/_game_guesses.html.slim
= turbo_frame_tag("guesses_frame") do
  .guesses-list
    h3 Previous Guesses:
    - @guesses.each do |guess|
      .guess-item
        = "Guess: #{guess.first_name} #{guess.last_name}, #{guess.player_target.position}, #{guess.player_target.team_name}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sportle" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Sportle">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>